spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/sample-db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    # Note that we use jdbc for Liquibase and r2dbc for the application
    url: jdbc:postgresql://postgres:5432/sample-db
    user: postgres
    password: postgres
