spring:
  r2dbc:
    # Use the environment variable R2DBC_URL if provided, otherwise default to H2
    url: ${R2DBC_URL:r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${R2DBC_USERNAME:sa}
    password: ${R2DBC_PASSWORD:}
  liquibase:
    enabled: true
    # Note that we use jdbc for Liquibase and r2dbc for the application
    url: ${LIQUIBASE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    user: ${LIQUIBASE_USER:sa}
    password: ${LIQUIBASE_PASSWORD:}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /
