spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  liquibase:
    enabled: true
    # Note that we use jdbc for Liquibase and r2dbc for the application
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    user: sa
    password:
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /
